CREATE TABLE `kindergarten_school` (
	`id` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`assessmentofchildrenslearningexperiences` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`curriculum_details` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`curriculumplanning` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`curriculumtype` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`exercise_book_workbooks` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`feelevelfullday` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`feelevelhalfday` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`joining_child_care_centre_subsidy_scheme` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`learning_teachingapproachandactivities` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`noofenrolmentaged2_3` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`providingextendedhoursservices` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`providingoccasionalchildcareservices` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`address` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`application_fee` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`application_form_download` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`application_period` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`ceceorabove` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`degree_holders` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`district` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`fax` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`image` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`image_top` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`indoor_playground` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`lattitude` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`location_no` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`longitude` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`lowerkgamsession` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`lowerkgamsessionfees` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`lowerkgpmsession` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`lowerkgpmsessionfees` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`lowerkgwdsession` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`lowerkgwdsessionfees` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`music_room` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`nameof_school_principal` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`nameof_school_supervisor` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`non_degree_holders` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`number_of_registered_classrooms` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`nurseryamsession` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`nurseryamsessionfees` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`nurserypmsession` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`nurserypmsessionfees` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`nurserywdsession` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`nurserywdsessionfees` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`other_activities_communication_with_parents` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`other_special_room` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`other_teacher_trainings` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`others` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`out_door_playground` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`parent_teacherassociation` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`qualified_assistant_kg_teachers` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`ratio_includes_classesaged23` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`registration_fee_half_daysession` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`registration_fee_whole_daysession` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`scale` INT(11) NOT NULL,
	`school_bag` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`school_category` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`school_categoury_title` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`school_discription` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`school_facilities` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`school_facilities_title` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`school_foundingyear` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`school_history` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`school_history_title` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`school_id` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`school_name` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`school_no` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`school_vision_and_mission` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`school_website` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`source` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`student_category` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`summer_uniform` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`support_to_students` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`tea_and_snacks` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`teacher_to_pupilratio_in_afternoon_session` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`teacher_to_pupilratio_in_morning_session` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`teaching_situation` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`school_fees` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`school_fees_title` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`teaching_situation_title` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`tel` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`text_boo0ks` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`time` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`totalamsession` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`total_no_of_permitte_accommodation_of_classroomsinuse` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`totalpmsession` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`totalwdsession` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`upperkgamsession` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`upperkgamsessionfees` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`upperkgpmsession` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`upperkgpmsessionfees` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`upperkgwdsession` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`upperkgwdsessionfees` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`winter_uniform` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`withchildcareservicesforchildrenagedunder2` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	PRIMARY KEY (`id`)
)
COLLATE='utf8mb4_unicode_ci'
ENGINE=InnoDB
AUTO_INCREMENT=0;


CREATE TABLE `primary_school` (
	`id` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`school_name` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`curriculum_tailoringand_adaptation` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`developmentof_generic_skills` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`developmentof_key_tasks` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`durationofeachnormalperiod` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`fee_remission_scheme` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`healthyschoollife` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`home_school_co_operation` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`incorporated_committee` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`learning_and_teaching_strategies` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`luncharrangement` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`lunchtime` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`numberof_school_daysperweek` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`numberofperiodsperday` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`others` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`remarks` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`school_ethos` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`school_development_plan` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`school_green_policy` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`school_management_organisation` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`schoolendsat` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`schools_major_concerns` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`schoolstartsat` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`teacher_professional_training_and_development` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`whole_school_approachto_caterfor_student_diversity` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`address` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`approval_preparation2013` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`approval_preparation2014` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`approval_preparation2015` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`approval_preparation2016` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`approval_preparation2017` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`approved_chargesforspecificpurposes` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`bachelor_degree` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`district` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`diversified_assessment_for_learning` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`facility_supportfor_studentswith_special_educational_needs` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`fax` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`feeder_secondary_school` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`hasthe_incorporatedmanagementcommitteebeenestablished` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`image` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`image_top` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`indoor_playground` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`lattitude` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`little_six2013` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`littlesix2014` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`littlesix2015` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`littlesix2016` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`littlesix2017` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`longitude` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`master_doctorate_degree_or_above` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`medium_of_instruction` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`nameof_school_principal` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`nominated_secondary_school` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`number_of_classroom` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`number_of_exam_per_year` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`number_of_library` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`number_of_school_hall` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`number_of_test_per_year` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`numberof_teachers_int_heapproved_establishment` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`other_charges` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`parent_teacher_association` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`religion` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`school_alumni_association` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`school_bus_service` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`school_category` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`school_categoury_title` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`school_discritpion` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`school_email` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`school_facilities` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`school_facilities_title` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`school_fee` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`school_history` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`school_history_title` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`school_id` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`school_motto` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`school_size` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`school_teachers2013` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`school_teachers2014` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`school_teachers2015` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`school_teachers2016` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`school_teachers2017` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`school_website` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`school_year2013` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`school_year2014` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`schoolyear2015` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`schoolyear2016` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`schoolyear2017` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`small_five2013` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`small_four2013` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`small_four2014` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`small_four2015` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`small_four2016` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`small_four2017` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`small_one2013` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`small_one2014` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`small_one2015` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`small_one2016` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`small_one2017` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`small_three2013` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`small_three2014` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`small_three2015` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`small_three2016` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`small_three2017` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`small_two2013` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`small_two2014` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`small_two2015` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`small_two2016` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`small_two2017` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`smallfive2014` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`smallfive2015` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`smallfive2016` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`smallfive2017` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`source` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`special_education_training` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`sponsoring_body` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`streaming_arrangement` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`student_gender` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`supervisor_chairmanof_management_committee` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`teacher_certificate_diploma_in_education` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`teaching_situation` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`teaching_situation_title` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`tel` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`through_train_secondary_school` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`time` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`tongfai` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`total2013` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`total2014` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`total2015` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`total2016` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`total2017` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`total_no_of_permitte_accommodation_of_classroomsinuse` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`totalnumber_ofteachersintheschool` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`work_experience0_4years` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`work_experience10yearso_or_above` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`work_experience5_9years` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`yearof_commencementof_operation` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	PRIMARY KEY (`id`)
)
COLLATE='utf8mb4_unicode_ci'
ENGINE=InnoDB
AUTO_INCREMENT=0;

CREATE TABLE `secondary_school` (
	`id` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`school_name` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`bachelor_degree` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`careerand_life_planning` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`chargesfor_specific_purposes` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`chineseasthemediumofinstruction` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`chineseasthemediumofinstruction0` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`chineseasthemediumofinstruction1` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`chineseasthemediumofinstruction2` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`directpublictransportationto_school` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`englishasthemediumofinstruction` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`englishasthemediumofinstruction0` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`englishasthemediumofinstruction1` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`englishasthemediumofinstruction2` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`extra_curricular_co_curricular_activities` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`facilityfor_supporting_studentswith_special_educational_needs` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`home_school_co_operation` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`incidentals` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`incorporated_management_committee` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`incorporated_management_committee_school_management` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`key_learning_areas` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`learning_and_teaching_strategies` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`learningand_assessment` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`master_doctorate_degreeorabove` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`numberofteachingpostsintheapprovedestablishment` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`orientation_activitiesand_healthy_life` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`other_charges` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`other_district` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`others` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`parent_teacher_association` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`parent_teacher_association_fee` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`past_students_association_school_alumni_association` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`principal` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`qualificationsand_professional_training` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`religion` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`remarks` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`school_development_plan` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`school_ethos` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`school_facilities` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`school_fee_remission` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`school_fees1` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`school_fees2` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`school_fees3` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`school_fees4` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`school_fees5` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`school_fees6` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`school_green_policy` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`school_management_organisation` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`school_motto` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`school_size` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`school_type` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`school_basedcurriculum` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`schools_key_concerns` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`secondary_one_admission` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`special_education_training` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`sponsoring_body` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`student_gender` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`student_union_association` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`students_association_membership_fee` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`subject_offeredin2017_2018school_year` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`subjects_offeredin2017and2018school_year` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`subjects_offeredin2017_2018school_year` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`subjectstobe_offeredin2018and2019school_year` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`subjectstobe_offeredin2018_2019school_year` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`supervisor_chairmanof_school_management_committee` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`teacher_certificate_diplomain_education` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`teacher_professional_training_and_development` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`tong_fais1` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`tong_fais2` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`tong_fais3` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`tong_fais4` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`tong_fais5` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`tong_fais6` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`totalnumberofteachersintheschool` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`usebygroup` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`usebygroup0` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`usebygroup1` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`usebygroup2` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`whole_school_approachto_caterfor_student_diversity` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`whole_school_language_policy` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`working_experiences` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`working_experiences0_4years` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`working_experiences10yearsorabove` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`working_experiences5_9years` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`yearof_commencementof_operation` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`address` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`approval_preparation2013` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`approval_preparation2014` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`approval_preparation2015` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`approval_preparation2016` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`approval_preparation2017` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`district` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`fax` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`image` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`image_top` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`lattitude` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`little_six2013` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`littlesix2014` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`littlesix2015` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`littlesix2016` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`littlesix2017` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`longitude` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`school_category` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`school_categoury_title` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`school_discritpion` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`school_email` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`school_history` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`school_history_title` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`school_id` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`school_teachers2013` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`school_teachers2014` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`school_teachers2015` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`school_teachers2016` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`school_teachers2017` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`school_website` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`school_year2013` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`school_year2014` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`schoolyear2015` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`schoolyear2016` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`schoolyear2017` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`small_five2013` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`small_four2013` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`small_four2014` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`small_four2015` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`small_four2016` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`small_four2017` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`small_one2013` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`small_one2014` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`small_one2015` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`small_one2016` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`small_one2017` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`small_three2013` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`small_three2014` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`small_three2015` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`small_three2016` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`small_three2017` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`small_two2013` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`small_two2014` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`small_two2015` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`small_two2016` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`small_two2017` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`smallfive2014` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`smallfive2015` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`smallfive2016` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`smallfive2017` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`source` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`teaching_situation` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`teaching_situation_title` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`tel` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`total2013` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`total2014` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`total2015` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`total2016` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	`total2017` LONGTEXT NULL COLLATE 'utf8mb4_unicode_ci',
	PRIMARY KEY (`id`)
)
COLLATE='utf8mb4_unicode_ci'
ENGINE=InnoDB
AUTO_INCREMENT=0;

ALTER TABLE `kindergarten_school`
	ADD COLUMN `created_on` DATETIME NULL,
	ADD COLUMN `updated_on` DATETIME NULL AFTER `created_on`;

ALTER TABLE `primary_school`
	ADD COLUMN `created_on` DATETIME NULL,
	ADD COLUMN `updated_on` DATETIME NULL AFTER `created_on`;

ALTER TABLE `secondary_school`
	ADD COLUMN `created_on` DATETIME NULL,
	ADD COLUMN `updated_on` DATETIME NULL AFTER `created_on`;

ALTER TABLE `primary_school`
	ADD COLUMN `school_network` LONGTEXT NULL AFTER `school_name`;
